# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: facdc247fafb93ff0c904801be9d92dbaa2d34604c33e891eb91dde222d4b7566b8b1ec4f49a291a31f6f7770a98e0b1e1ad1f48970dda265f6e4f3ad213fb0f

test:
  secret_key_base: 618ce0736c62e79e30392455a20efe06a6102ca03b6af73a9ce22a58e03b40aec3933dcba30c8355b15d488b4b9ea16524717544e25de4b4dc200924cdeb37ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
